### PR TITLE
do not use global variable `Buffer` directly

### PR DESCRIPTION
**Pull request by nicolaspanel**
use `require('buffer').Buffer` instead

### CODE REVIEW

**Comment by gre** [comment]
got bit by this, wondering what should be done as https://github.com/mikolalysenko/typedarray-pool/issues/3 state that Buffer dep should be removed?

**Comment by dy** [comment]
@mikolalysenko ping

**Comment by dy** [comment]
@mikolalysenko any chance we can merge this? That becomes a blocker in many dependent packages.

**Comment by jphilipstevens** [comment]
Seems this causes an issue if your users/clients do not have buffer as a node_module. We were hit by this by accident when AppCenter was not obeying our lock files and typedarray pool was updated to 1.2.0 

Can you add this as either a dependency or peer dep?

**Pull request merged**
